osx_image: xcode8.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
before_install:
- mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([
  "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz
  | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends
  -y icnsutils graphicsmagick xz-utils; fi
install:
- nvm install 6
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- npm install -g xvfb-maybe
- yarn
script:
- yarn run build
branches:
  only:
  - master
notifications:
  pushover:
    api_key:
      secure: cTjk9q9ABZrC1AQcusYQbPLi9a9PVgH9cHjOoLLF/8MYf9CmXpLYbjovQq4YfrMAa/S0FMgFmxOlJb150OyPcA1GyPtz+uvWbVqC1RBJRvS2R+eQk/PDpOZgu4DBE1J+LHJMWIy9tiYTJvLLgYwQKT/lzcWCpO6RTOmVsxr0umgFtGr8Hn59NRLvmUOVw1FOVqa6rLSZTg5Bc5oDq/GWzxAo8GiSAs0jeUe5mncaKf2MSDrMp/tlgj7s7TX745bsqciMNOIyyLLLiFOucu+V54VqtHqtgW4vGWrtJrAH0nalGfzxPFw3cZOD8KX7MolNeb7By/5taNrn6PWX66xfwWyyKJgbYuXVj7bZXMfOU3NVa7/HGMZ/mtXHwXBW6ohX399u1/WzlGuVtH7gMbwBqhdRU2tyMFhgyeinacJN//RnswXLyq0QDqQ307vS3ZOLE6sbS7MaAR1jT6r/bOHEJDY6CIIV0rt25xtHmZLEw6THTqk71LjXnbDWMoEIBudvmfK1lfP9Dbqk2562WZrqNfipzhRv+EJzh2HDBI+it3vKEUuLUlyFMETDwSi2k/okVCcrM00uoMkD1SNcD/OX346VvGx35cwSV43FrX5qiP9WjWoRRiQUMiieXpaA0SJ9OTyFV8E1zGkJgxCuj+euXKs8ceNJNhoHT+oLiaQP078=
    users:
      secure: oaV7ZHZ3m5H6JnZ7YMAWeAuCnIF9tYPhspYcxclYX3jlKKgQiPrbnfYRDP8qEUQRNOtLxCIqX8euN6eoyvaQ7IX/O+Kty5l3XimwXpwFRY46qoA99Gs1zznLlBTCtqXKj6S5V6r9ynj3OcHqbLWcJTF1ui8AnDMB1wzI+4reUzFIBDo3LBFs+XO9W0Ibs4ziwUSbotP225DtxyUV7d/YwvEkQ9ZfPQCohnA0HBXVCLGKPEMwFvBBHGt+/39DNh7imXjhOBJzvvWmFplzRKEwzUxqitm2Vv816OrWi/1xJrPsiZKoy/gkPrakDLRbGn45Qmvtp2E1EasyVUDuzP2V6X31G1pYdr86OGf+WXUuxygK4v1VrDPznN5SbW4Rfxri4e1hTsVAOtYxPUUYnpfCIMMXWnr1aeVQcgIhW8P2jq1/Ju+m/fTFRBfT/f+tmCoKtTdCPwJMCj1xtezZvu1KWLWs1ECkaGxs1tAJhsBgHA8QihkClf03s0F/IG7cvRkOYlyhCgis6xYqrTggFX9C91i6G8Xt9i0lATCm+LMFU22Po9nAS4NZriGm/rFodTfdA3P5G22Aj+5s53w4B/0j3LD+/aAs1N9/okIbsf1uWu/Y1rvYKcPb1lixu1zrYrSmonf1JSSI+C517uctDvJyTPWaMZewzXItdyvL0UEf6Ps=
