version: 0.1.{build}

branches:
  only:
    - master

image: Visual Studio 2017
platform:
  - x64

artifacts:
  - path: '.\build\G-Suite Tool Setup *.exe'

deploy:
  - provider: GitHub
    release: $(appveyor_repo_tag_name)
    artifact:  win-release.zip    #this should be the same as a path in artifact
    draft: true
    prerelease: true
    auth_token:
      secure: plxuSU39QZX5LXsgEFU43zakkpudQ0/mLt0at+GmwW//la6vbXEvuGssWAGnWrW5
    on:
      appveyor_repo_tag: true

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - git reset --hard HEAD
  - yarn
  - node --version

build_script:
  - yarn build

test: off
